### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by tmcgilchrist** [dmbaturin/otoml#1]
Could you add a CHANGELOG for this library?

Thanks for the library, I've started using it for a new project and am finding it very useful.

**Comment by dmbaturin** [comment]
Yes, it's a good point. I was going to add it for the 0.9.1 release but forgot about it, added it now.

0.9.1 is a small bugfix related to the signatures of the default implementation modules—I forgot `with type t = ...` in the first version so those types ended up unintentionally abstract.

**Comment by tmcgilchrist** [comment]
Thank you.

**Comment by dmbaturin** [comment]
What's the project, by the way? Is it public?

**Comment by tmcgilchrist** [comment]
Nothing public right now.
I'm using Toml for configuration files.

**Comment by dmbaturin** [comment]
If you see any bugs or missing useful functionality in the API, let me know.
