### ISSUE TITLE
Duplicate_key exception escapes Parser.from_string_result

### ISSUE THREAD

**Issue by mooreryan** [dmbaturin/otoml#3]
Question about the difference in the way `Duplicate_key` vs `Parse_error` is handled in `Parser.from_string_result`.

When a key is duplicated you get a duplicate key error.

```ocaml
let s = {|
[foo]
a = 1
a = 2
|}

let toml = Otoml.Parser.from_string s

Exception:
Otoml__Otoml_base.Make(N)(D).Parser.Duplicate_key("duplicate key \"a\" overrides a value of type integer with a value of type integer").
```

Makes sense...the toml spec says same key multiple times is invalid:

> Defining a key multiple times is invalid.  ([link](https://toml.io/en/v1.0.0#keys))

I would expect this error to get caught when using `Parser.from_string_result`, though it does not.  Here's the code for that function for reference (sorry I don't have link to it, I got the code by browsing the local source):

```ocaml
    let from_string_result s =
      try Ok (from_string s)
      with
      | Parse_error (pos, err) -> Error (format_parse_error pos err)
      | Failure err -> Error (Printf.sprintf "otoml internal error: %s" err)
```

Catches other errors, but not `Duplicate_key`.

For comparison, if a table is defined more than once, it's a `Parse_error`

```ocaml
	if p = p' then Printf.ksprintf (parse_error None) "table [%s] is defined more than once"
```

which would does get caught in the `from_string_result` (unlike duplicate key error).

Just to go back to the toml spec again

> Like keys, you cannot define a table more than once. Doing so is invalid. ([link](https://toml.io/en/v1.0.0#table))

Okay, so no duplicating tables and no duplicating keys.  Sounds good.

My question is, is there a reason that the `Duplicate_key` exception is not caught in `from_string_result` but `Parse_error` is?  Another way to put it is, why the duplicate table problem is caught in the `from_string_result`, but the duplicate key exception escapes?

(Thanks for the library by the way...been using it in multiple projects.)

**Comment by dmbaturin** [comment]
There's no reason at all! It's my oversight, plain and simple. As I remember, I got an idea to add a distinct duplicate error pretty late in the development process and evidently failed to integrate it properly.

I'll fix it tomorrow and make a maintenance release.

**Comment by dmbaturin** [comment]
@mooreryan There was one more problem with the dupliucate key exception: it wasn't properly exposed in the module interface even. I think I got it sorted now, please test if you got time.

**Comment by mooreryan** [comment]
Thanks for the quick response! 

I just pinned the main branch from github and reran the code which was giving me the issues...seems all good now.

**Comment by dmbaturin** [comment]
@mooreryan Thanks! I'll do a bit more testing and make an OPAM release then.

**Comment by dmbaturin** [comment]
Closing since all the changes were already included in the release (long overdue ;).
